import { db, wilayasTable, pharmaciesTable, doctorsTable } from "@workspace/db";

const wilayas = [
  { id: 1, code: "01", name: "Adrar", name_ar: "أدرار", region: "Sud" },
  { id: 2, code: "02", name: "Chlef", name_ar: "الشلف", region: "Centre-Ouest" },
  { id: 3, code: "03", name: "Laghouat", name_ar: "الأغواط", region: "Centre-Sud" },
  { id: 4, code: "04", name: "Oum El Bouaghi", name_ar: "أم البواقي", region: "Est" },
  { id: 5, code: "05", name: "Batna", name_ar: "باتنة", region: "Est" },
  { id: 6, code: "06", name: "Béjaïa", name_ar: "بجاية", region: "Est" },
  { id: 7, code: "07", name: "Biskra", name_ar: "بسكرة", region: "Sud-Est" },
  { id: 8, code: "08", name: "Béchar", name_ar: "بشار", region: "Sud-Ouest" },
  { id: 9, code: "09", name: "Blida", name_ar: "البليدة", region: "Centre" },
  { id: 10, code: "10", name: "Bouira", name_ar: "البويرة", region: "Centre" },
  { id: 11, code: "11", name: "Tamanrasset", name_ar: "تمنراست", region: "Grand-Sud" },
  { id: 12, code: "12", name: "Tébessa", name_ar: "تبسة", region: "Est" },
  { id: 13, code: "13", name: "Tlemcen", name_ar: "تلمسان", region: "Ouest" },
  { id: 14, code: "14", name: "Tiaret", name_ar: "تيارت", region: "Ouest" },
  { id: 15, code: "15", name: "Tizi Ouzou", name_ar: "تيزي وزو", region: "Centre-Est" },
  { id: 16, code: "16", name: "Alger", name_ar: "الجزائر", region: "Centre" },
  { id: 17, code: "17", name: "Djelfa", name_ar: "الجلفة", region: "Centre-Sud" },
  { id: 18, code: "18", name: "Jijel", name_ar: "جيجل", region: "Est" },
  { id: 19, code: "19", name: "Sétif", name_ar: "سطيف", region: "Est" },
  { id: 20, code: "20", name: "Saïda", name_ar: "سعيدة", region: "Ouest" },
  { id: 21, code: "21", name: "Skikda", name_ar: "سكيكدة", region: "Est" },
  { id: 22, code: "22", name: "Sidi Bel Abbès", name_ar: "سيدي بلعباس", region: "Ouest" },
  { id: 23, code: "23", name: "Annaba", name_ar: "عنابة", region: "Est" },
  { id: 24, code: "24", name: "Guelma", name_ar: "قالمة", region: "Est" },
  { id: 25, code: "25", name: "Constantine", name_ar: "قسنطينة", region: "Est" },
  { id: 26, code: "26", name: "Médéa", name_ar: "المدية", region: "Centre" },
  { id: 27, code: "27", name: "Mostaganem", name_ar: "مستغانم", region: "Ouest" },
  { id: 28, code: "28", name: "M'Sila", name_ar: "المسيلة", region: "Centre-Est" },
  { id: 29, code: "29", name: "Mascara", name_ar: "معسكر", region: "Ouest" },
  { id: 30, code: "30", name: "Ouargla", name_ar: "ورقلة", region: "Sud" },
  { id: 31, code: "31", name: "Oran", name_ar: "وهران", region: "Ouest" },
  { id: 32, code: "32", name: "El Bayadh", name_ar: "البيض", region: "Ouest-Sud" },
  { id: 33, code: "33", name: "Illizi", name_ar: "إليزي", region: "Grand-Sud" },
  { id: 34, code: "34", name: "Bordj Bou Arréridj", name_ar: "برج بوعريريج", region: "Centre-Est" },
  { id: 35, code: "35", name: "Boumerdès", name_ar: "بومرداس", region: "Centre" },
  { id: 36, code: "36", name: "El Tarf", name_ar: "الطارف", region: "Est" },
  { id: 37, code: "37", name: "Tindouf", name_ar: "تندوف", region: "Grand-Sud" },
  { id: 38, code: "38", name: "Tissemsilt", name_ar: "تيسمسيلت", region: "Ouest" },
  { id: 39, code: "39", name: "El Oued", name_ar: "الوادي", region: "Sud-Est" },
  { id: 40, code: "40", name: "Khenchela", name_ar: "خنشلة", region: "Est" },
  { id: 41, code: "41", name: "Souk Ahras", name_ar: "سوق أهراس", region: "Est" },
  { id: 42, code: "42", name: "Tipaza", name_ar: "تيبازة", region: "Centre" },
  { id: 43, code: "43", name: "Mila", name_ar: "ميلة", region: "Est" },
  { id: 44, code: "44", name: "Aïn Defla", name_ar: "عين الدفلى", region: "Centre-Ouest" },
  { id: 45, code: "45", name: "Naâma", name_ar: "النعامة", region: "Ouest-Sud" },
  { id: 46, code: "46", name: "Aïn Témouchent", name_ar: "عين تموشنت", region: "Ouest" },
  { id: 47, code: "47", name: "Ghardaïa", name_ar: "غرداية", region: "Sud" },
  { id: 48, code: "48", name: "Relizane", name_ar: "غليزان", region: "Ouest" },
  { id: 49, code: "49", name: "Timimoun", name_ar: "تيميمون", region: "Grand-Sud" },
  { id: 50, code: "50", name: "Bordj Badji Mokhtar", name_ar: "برج باجي مختار", region: "Grand-Sud" },
  { id: 51, code: "51", name: "Ouled Djellal", name_ar: "أولاد جلال", region: "Sud-Est" },
  { id: 52, code: "52", name: "Béni Abbès", name_ar: "بني عباس", region: "Sud-Ouest" },
  { id: 53, code: "53", name: "In Salah", name_ar: "عين صالح", region: "Grand-Sud" },
  { id: 54, code: "54", name: "In Guezzam", name_ar: "عين قزام", region: "Grand-Sud" },
  { id: 55, code: "55", name: "Touggourt", name_ar: "تقرت", region: "Sud-Est" },
  { id: 56, code: "56", name: "Djanet", name_ar: "جانت", region: "Grand-Sud" },
  { id: 57, code: "57", name: "El M'Ghair", name_ar: "المغير", region: "Sud-Est" },
  { id: 58, code: "58", name: "El Menia", name_ar: "المنيعة", region: "Sud" },
];

const pharmacies = [
  { name: "Pharmacie El Amine", name_ar: "صيدلية الأمين", address: "12 Rue Didouche Mourad, Alger-Centre", commune: "Alger-Centre", wilaya_id: 16, phone: "021 63 44 12", phone2: "0550 23 11 45", email: "elamine.pharma@gmail.com", hours_open: "08:00", hours_close: "22:00", is_24h: false, on_duty: true, on_duty_until: "Demain 08:00", rating: 4.5, review_count: 128, services: ["Garde de nuit", "Livraison", "Prise de tension"], latitude: 36.7725, longitude: 3.0593 },
  { name: "Pharmacie Centrale Oran", name_ar: "الصيدلية المركزية وهران", address: "45 Boulevard Millenium, Oran", commune: "Oran", wilaya_id: 31, phone: "041 28 55 30", phone2: "0770 12 33 99", email: "centrale.oran@gmail.com", hours_open: "08:00", hours_close: "21:00", is_24h: false, on_duty: false, rating: 4.2, review_count: 87, services: ["Parapharmacie", "Matériel médical", "Prise de tension"], latitude: 35.6971, longitude: -0.6308 },
  { name: "Pharmacie Ben Amar", name_ar: "صيدلية بن عمار", address: "8 Rue des Frères Aïssaoui, Constantine", commune: "Constantine", wilaya_id: 25, phone: "031 67 22 10", on_duty: true, on_duty_until: "Dimanche 08:00", hours_open: "08:00", hours_close: "20:00", is_24h: false, rating: 4.7, review_count: 203, services: ["Garde", "Ordonnances urgentes"], latitude: 36.3648, longitude: 6.6147 },
  { name: "Pharmacie 24H Annaba", name_ar: "صيدلية 24 ساعة عنابة", address: "Cité Sakiet Sidi Youcef, Annaba", commune: "Annaba", wilaya_id: 23, phone: "038 87 41 22", phone2: "0661 98 77 54", is_24h: true, on_duty: true, hours_open: "00:00", hours_close: "23:59", rating: 4.8, review_count: 312, services: ["Ouvert 24H/24", "Urgences", "Garde de nuit", "Livraison nocturne"], latitude: 36.9064, longitude: 7.7539 },
  { name: "Pharmacie Sétif Santé", name_ar: "صيدلية سطيف الصحة", address: "Place de l'Indépendance, Sétif", commune: "Sétif", wilaya_id: 19, phone: "036 84 12 55", on_duty: false, hours_open: "08:30", hours_close: "20:30", is_24h: false, rating: 4.0, review_count: 65, services: ["Parapharmacie", "Matériel médical"], latitude: 36.1898, longitude: 5.4078 },
  { name: "Pharmacie du Midi Tlemcen", name_ar: "صيدلية الظهيرة تلمسان", address: "Rue de la République, Tlemcen", commune: "Tlemcen", wilaya_id: 13, phone: "043 26 78 90", on_duty: true, on_duty_until: "Lundi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.3, review_count: 91, services: ["Garde", "Homéopathie", "Prise de tension"], latitude: 34.8824, longitude: -1.3156 },
  { name: "Pharmacie Blida El Shifa", name_ar: "صيدلية البليدة الشفاء", address: "Boulevard Colonel Amirouche, Blida", commune: "Blida", wilaya_id: 9, phone: "025 40 17 33", on_duty: false, hours_open: "08:00", hours_close: "20:00", is_24h: false, rating: 4.1, review_count: 78, services: ["Parapharmacie", "Matériel bébé"], latitude: 36.4686, longitude: 2.8277 },
  { name: "Pharmacie Béjaïa Côte", name_ar: "صيدلية بجاية الساحل", address: "Rue Larbi Ben M'Hidi, Béjaïa", commune: "Béjaïa", wilaya_id: 6, phone: "034 21 56 78", on_duty: true, on_duty_until: "Samedi 08:00", hours_open: "08:00", hours_close: "22:00", is_24h: false, rating: 4.6, review_count: 143, services: ["Garde", "Diététique", "Phytothérapie"], latitude: 36.7509, longitude: 5.0564 },
  { name: "Pharmacie El Wiam Batna", name_ar: "صيدلية الوئام باتنة", address: "Rue Mostefa Ben Boulaïd, Batna", commune: "Batna", wilaya_id: 5, phone: "033 86 44 00", on_duty: false, hours_open: "08:00", hours_close: "21:30", is_24h: false, rating: 4.4, review_count: 110, services: ["Parapharmacie", "Matériel médical", "Conseils"], latitude: 35.5560, longitude: 6.1750 },
  { name: "Pharmacie Ghardaïa Oasis", name_ar: "صيدلية غرداية الواحة", address: "Place du 1er Novembre, Ghardaïa", commune: "Ghardaïa", wilaya_id: 47, phone: "029 87 12 34", on_duty: true, on_duty_until: "Mercredi 08:00", hours_open: "08:00", hours_close: "20:00", is_24h: false, rating: 4.2, review_count: 55, services: ["Garde", "Phytothérapie", "Médecine traditionnelle"], latitude: 32.4897, longitude: 3.6744 },
  { name: "Pharmacie Biskra Desert", name_ar: "صيدلية بسكرة الصحراء", address: "Rue Ziane Achour, Biskra", commune: "Biskra", wilaya_id: 7, phone: "033 74 22 80", on_duty: false, hours_open: "08:30", hours_close: "20:30", is_24h: false, rating: 3.9, review_count: 42, services: ["Parapharmacie"], latitude: 34.8500, longitude: 5.7270 },
  { name: "Pharmacie Tizi Ouzou Amizour", name_ar: "صيدلية تيزي وزو أميزور", address: "Avenue de la Liberté, Tizi Ouzou", commune: "Tizi Ouzou", wilaya_id: 15, phone: "026 21 44 67", on_duty: true, on_duty_until: "Jeudi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.5, review_count: 167, services: ["Garde", "Parapharmacie", "Prise de tension", "Test glycémie"], latitude: 36.7112, longitude: 4.0450 },
  { name: "Pharmacie Sidi Bel Abbès Nord", name_ar: "صيدلية سيدي بلعباس الشمال", address: "Rue du 1er Novembre, Sidi Bel Abbès", commune: "Sidi Bel Abbès", wilaya_id: 22, phone: "048 72 33 55", on_duty: false, hours_open: "08:00", hours_close: "19:30", is_24h: false, rating: 4.0, review_count: 72, services: ["Parapharmacie", "Matériel bébé"], latitude: 35.1896, longitude: -0.6307 },
  { name: "Pharmacie Jijel Marine", name_ar: "صيدلية جيجل البحرية", address: "Boulevard du 20 Août, Jijel", commune: "Jijel", wilaya_id: 18, phone: "034 46 88 20", on_duty: true, on_duty_until: "Vendredi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.3, review_count: 89, services: ["Garde", "Dermocosmétique"], latitude: 36.8200, longitude: 5.7667 },
  { name: "Pharmacie Boumerdès Centre", name_ar: "صيدلية بومرداس المركز", address: "Cité 500 Logements, Boumerdès", commune: "Boumerdès", wilaya_id: 35, phone: "024 81 22 40", on_duty: false, hours_open: "08:30", hours_close: "20:00", is_24h: false, rating: 4.1, review_count: 58, services: ["Parapharmacie", "Conseils"], latitude: 36.7631, longitude: 3.4765 },
  { name: "Pharmacie El Khaldounya Ouargla", name_ar: "صيدلية الخلدونية ورقلة", address: "Rue Ibn Khaldoun, Ouargla", commune: "Ouargla", wilaya_id: 30, phone: "029 70 45 88", on_duty: true, on_duty_until: "Mardi 08:00", hours_open: "08:00", hours_close: "20:00", is_24h: false, rating: 4.4, review_count: 76, services: ["Garde", "Phytothérapie", "Test glycémie"], latitude: 31.9539, longitude: 5.3353 },
  { name: "Pharmacie Médéa El Baraka", name_ar: "صيدلية المدية البركة", address: "Place du 1er Mai, Médéa", commune: "Médéa", wilaya_id: 26, phone: "025 58 33 17", on_duty: false, hours_open: "08:00", hours_close: "20:30", is_24h: false, rating: 3.8, review_count: 34, services: ["Parapharmacie"], latitude: 36.2638, longitude: 2.7506 },
  { name: "Pharmacie Tipaza Aqua", name_ar: "صيدلية تيبازة الأكوا", address: "Boulevard de la Mer, Tipaza", commune: "Tipaza", wilaya_id: 42, phone: "024 47 11 90", on_duty: true, on_duty_until: "Lundi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.3, review_count: 62, services: ["Garde", "Dermocosmétique", "Prise de tension"], latitude: 36.5897, longitude: 2.4490 },
  { name: "Pharmacie Mascara El Feth", name_ar: "صيدلية معسكر الفتح", address: "Rue Abdelkader, Mascara", commune: "Mascara", wilaya_id: 29, phone: "045 80 22 33", on_duty: false, hours_open: "08:00", hours_close: "19:00", is_24h: false, rating: 3.9, review_count: 28, services: ["Parapharmacie"], latitude: 35.3973, longitude: 0.1415 },
  { name: "Pharmacie Guelma Lumière", name_ar: "صيدلية قالمة النور", address: "Avenue Souidani Boudjemaa, Guelma", commune: "Guelma", wilaya_id: 24, phone: "037 21 55 88", on_duty: true, on_duty_until: "Dimanche 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.5, review_count: 97, services: ["Garde", "Matériel médical", "Prise de tension"], latitude: 36.4622, longitude: 7.4315 },
  { name: "Pharmacie Chlef El Amel", name_ar: "صيدلية الشلف الأمل", address: "Rue de la Révolution, Chlef", commune: "Chlef", wilaya_id: 2, phone: "027 72 11 44", on_duty: false, hours_open: "08:00", hours_close: "20:00", is_24h: false, rating: 4.0, review_count: 51, services: ["Parapharmacie", "Matériel bébé"], latitude: 36.1650, longitude: 1.3320 },
  { name: "Pharmacie Mostaganem Riviera", name_ar: "صيدلية مستغانم ريفيرا", address: "Boulevard Front de Mer, Mostaganem", commune: "Mostaganem", wilaya_id: 27, phone: "045 21 88 70", on_duty: true, on_duty_until: "Samedi 08:00", hours_open: "08:00", hours_close: "21:30", is_24h: false, rating: 4.4, review_count: 84, services: ["Garde", "Dermocosmétique"], latitude: 35.9316, longitude: 0.0869 },
  { name: "Pharmacie Skikda Nordique", name_ar: "صيدلية سكيكدة الشمالية", address: "Place du 7 Août, Skikda", commune: "Skikda", wilaya_id: 21, phone: "038 75 33 10", on_duty: false, hours_open: "08:30", hours_close: "20:00", is_24h: false, rating: 4.1, review_count: 69, services: ["Parapharmacie", "Conseils"], latitude: 36.8783, longitude: 6.9003 },
  { name: "Pharmacie M'Sila El Hilal", name_ar: "صيدلية المسيلة الهلال", address: "Cité Soumaa, M'Sila", commune: "M'Sila", wilaya_id: 28, phone: "035 55 66 77", on_duty: true, on_duty_until: "Jeudi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.2, review_count: 73, services: ["Garde", "Phytothérapie"], latitude: 35.7056, longitude: 4.5439 },
  { name: "Pharmacie Tamanrasset Sahara", name_ar: "صيدلية تمنراست الصحراء", address: "Place Centrale, Tamanrasset", commune: "Tamanrasset", wilaya_id: 11, phone: "029 34 11 22", on_duty: false, hours_open: "08:00", hours_close: "20:00", is_24h: false, rating: 4.3, review_count: 45, services: ["Phytothérapie", "Médecine traditionnelle"], latitude: 22.7851, longitude: 5.5228 },
  { name: "Pharmacie El Oued Palmeraie", name_ar: "صيدلية الوادي النخيل", address: "Boulevard Mohammed Boudiaf, El Oued", commune: "El Oued", wilaya_id: 39, phone: "032 21 44 56", on_duty: true, on_duty_until: "Vendredi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.1, review_count: 60, services: ["Garde", "Parapharmacie"], latitude: 33.3683, longitude: 6.8631 },
  { name: "Pharmacie Bab El Oued Alger", name_ar: "صيدلية باب الواد الجزائر", address: "Rue Khemisti, Bab El Oued, Alger", commune: "Bab El Oued", wilaya_id: 16, phone: "021 96 32 10", on_duty: false, hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.6, review_count: 198, services: ["Parapharmacie", "Livraison", "Test glycémie", "Prise de tension"], latitude: 36.7801, longitude: 3.0445 },
  { name: "Pharmacie Hydra Prestige", name_ar: "صيدلية حيدرة الفاخرة", address: "Avenue des Frères Bouadou, Hydra, Alger", commune: "Hydra", wilaya_id: 16, phone: "021 48 77 30", phone2: "0770 88 90 12", email: "pharma.hydra@yahoo.fr", is_24h: true, on_duty: true, on_duty_until: "Demain 08:00", hours_open: "00:00", hours_close: "23:59", rating: 4.9, review_count: 376, services: ["Ouvert 24H/24", "Garde de nuit", "Parapharmacie premium", "Livraison", "Dermocosmétique", "Test glycémie", "Prise de tension"], latitude: 36.7427, longitude: 3.0427 },
  { name: "Pharmacie Ain Beïda Oum El Bouaghi", name_ar: "صيدلية عين البيضاء أم البواقي", address: "Rue Houari Boumediene, Ain Beïda", commune: "Ain Beïda", wilaya_id: 4, phone: "032 52 11 40", on_duty: false, hours_open: "08:00", hours_close: "19:30", is_24h: false, rating: 3.7, review_count: 22, services: ["Parapharmacie"], latitude: 35.7952, longitude: 7.3946 },
  { name: "Pharmacie Relizane Al Nour", name_ar: "صيدلية غليزان النور", address: "Boulevard de la Soummam, Relizane", commune: "Relizane", wilaya_id: 48, phone: "046 90 12 34", on_duty: true, on_duty_until: "Mercredi 08:00", hours_open: "08:00", hours_close: "21:00", is_24h: false, rating: 4.0, review_count: 47, services: ["Garde", "Parapharmacie"], latitude: 35.7373, longitude: 0.5555 },
];

const doctors = [
  { first_name: "Karim", last_name: "Benali", title: "Dr.", specialty: "Médecine générale", specialty_ar: "طب عام", address: "12 Rue Didouche Mourad, Alger-Centre", commune: "Alger-Centre", wilaya_id: 16, phone: "021 63 50 30", consultation_hours: "Lun-Sam: 09:00-12:00, 14:00-17:00", consultation_fee: 1500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.6, review_count: 215, experience_years: 18, bio: "Médecin généraliste avec 18 ans d'expérience, spécialisé dans le suivi des maladies chroniques et la médecine préventive. Diplômé de la Faculté de Médecine d'Alger.", available_today: true, latitude: 36.7725, longitude: 3.0593 },
  { first_name: "Nadia", last_name: "Cherif", title: "Dr.", specialty: "Pédiatrie", specialty_ar: "طب الأطفال", address: "Cité Diar El Mahçoul, El Harrach, Alger", commune: "El Harrach", wilaya_id: 16, phone: "021 52 10 44", phone2: "0550 90 11 22", consultation_hours: "Lun-Ven: 09:00-13:00, 15:00-18:00", consultation_fee: 2000, accepts_cnas: true, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.8, review_count: 342, experience_years: 12, bio: "Pédiatre passionnée par la santé de l'enfant de la naissance à l'adolescence. Spécialiste en nutrition pédiatrique et développement de l'enfant.", available_today: true, latitude: 36.7242, longitude: 3.1009 },
  { first_name: "Mohamed", last_name: "Hadj Aissa", title: "Pr.", specialty: "Cardiologie", specialty_ar: "أمراض القلب", address: "CHU Mustapha Pacha, Alger", commune: "Alger-Centre", wilaya_id: 16, phone: "021 23 81 00", consultation_hours: "Mar-Jeu: 09:00-12:00", consultation_fee: 4000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français", "Anglais"], rating: 4.9, review_count: 512, experience_years: 30, bio: "Professeur agrégé en cardiologie, chef de service au CHU Mustapha Pacha. Expert en cardiologie interventionnelle et électrophysiologie.", available_today: false, latitude: 36.7588, longitude: 3.0603 },
  { first_name: "Samira", last_name: "Bouzidi", title: "Dr.", specialty: "Dermatologie", specialty_ar: "أمراض الجلد", sub_specialty: "Cosmétologie médicale", address: "67 Avenue de Pékin, Hydra, Alger", commune: "Hydra", wilaya_id: 16, phone: "021 48 99 00", email: "dr.bouzidi@gmail.com", consultation_hours: "Lun-Sam: 10:00-18:00", consultation_fee: 3000, accepts_cnas: false, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.7, review_count: 289, experience_years: 15, bio: "Dermatologue et cosmétologue médicale. Spécialiste dans le traitement des maladies de la peau, l'acné, le psoriasis et la dermatologie esthétique.", available_today: true, latitude: 36.7427, longitude: 3.0427 },
  { first_name: "Rachid", last_name: "Mebarki", title: "Dr.", specialty: "Ophtalmologie", specialty_ar: "طب العيون", address: "Rue Colonel Amirouche, Oran", commune: "Oran", wilaya_id: 31, phone: "041 34 22 50", consultation_hours: "Dim-Jeu: 08:30-12:30, 14:00-17:00", consultation_fee: 2500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.5, review_count: 178, experience_years: 20, bio: "Ophtalmologiste avec expertise en chirurgie réfractive, cataracte et glaucome. Formé en France et en Espagne.", available_today: true, latitude: 35.6971, longitude: -0.6308 },
  { first_name: "Fatima Zohra", last_name: "Laib", title: "Dr.", specialty: "Gynécologie-Obstétrique", specialty_ar: "أمراض النساء والتوليد", address: "Clinique El Madina, Oran", commune: "Oran", wilaya_id: 31, phone: "041 29 44 70", phone2: "0770 55 88 11", consultation_hours: "Lun-Sam: 09:00-17:00 (urgences 24h)", consultation_fee: 3500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.9, review_count: 423, experience_years: 16, bio: "Gynécologue-obstétricienne avec expertise en grossesse à haut risque, infertilité et chirurgie coelioscopique.", available_today: true, latitude: 35.7050, longitude: -0.6200 },
  { first_name: "Ahmed", last_name: "Meziani", title: "Dr.", specialty: "Neurologie", specialty_ar: "أمراض الأعصاب", address: "CHU Constantine Ibn Badis, Constantine", commune: "Constantine", wilaya_id: 25, phone: "031 92 31 00", consultation_hours: "Dim-Mer: 09:00-12:00", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français", "Anglais"], rating: 4.7, review_count: 197, experience_years: 22, bio: "Neurologue spécialisé dans les maladies neurodégénératives, l'épilepsie et la sclérose en plaques. Chef de service au CHU de Constantine.", available_today: false, latitude: 36.3648, longitude: 6.6147 },
  { first_name: "Leila", last_name: "Ferhat", title: "Dr.", specialty: "Médecine interne", specialty_ar: "الطب الباطني", address: "Rue Pasteur, Constantine", commune: "Constantine", wilaya_id: 25, phone: "031 64 12 88", consultation_hours: "Lun-Ven: 09:00-16:00", consultation_fee: 2000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.4, review_count: 134, experience_years: 14, bio: "Interniste avec expérience dans le diagnostic et le traitement des maladies systémiques complexes, diabète et hypertension.", available_today: true, latitude: 36.3700, longitude: 6.6200 },
  { first_name: "Yacine", last_name: "Tabet", title: "Dr.", specialty: "Orthopédie-Traumatologie", specialty_ar: "جراحة العظام", address: "Clinique Ibnou Sina, Annaba", commune: "Annaba", wilaya_id: 23, phone: "038 86 44 00", consultation_hours: "Dim-Jeu: 08:30-13:00, 15:00-18:30", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.6, review_count: 231, experience_years: 19, bio: "Chirurgien orthopédiste spécialisé en traumatologie du sport, chirurgie prothétique du genou et de la hanche.", available_today: true, latitude: 36.9064, longitude: 7.7539 },
  { first_name: "Houria", last_name: "Amrani", title: "Dr.", specialty: "Psychiatrie", specialty_ar: "الطب النفسي", address: "Clinique Les Jasmin, Sétif", commune: "Sétif", wilaya_id: 19, phone: "036 91 22 40", consultation_hours: "Lun-Ven: 10:00-17:00", consultation_fee: 2500, accepts_cnas: false, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.8, review_count: 167, experience_years: 13, bio: "Psychiatre clinicienne spécialisée dans les troubles anxieux, dépressifs et les thérapies comportementales et cognitives (TCC).", available_today: true, latitude: 36.1898, longitude: 5.4078 },
  { first_name: "Omar", last_name: "Belkaid", title: "Pr.", specialty: "Pneumologie", specialty_ar: "أمراض الرئة", address: "EHU 1er Novembre, Oran", commune: "Oran", wilaya_id: 31, phone: "041 41 91 00", consultation_hours: "Dim-Mar: 09:00-12:00", consultation_fee: 4000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français", "Espagnol"], rating: 4.9, review_count: 389, experience_years: 28, bio: "Professeur en pneumologie et allergologie. Expert dans le traitement de l'asthme, BPCO, et maladies respiratoires infectieuses.", available_today: false, latitude: 35.7100, longitude: -0.6100 },
  { first_name: "Dalila", last_name: "Benouakta", title: "Dr.", specialty: "Endocrinologie", specialty_ar: "أمراض الغدد الصماء", address: "Cabinet Médical Soummam, Béjaïa", commune: "Béjaïa", wilaya_id: 6, phone: "034 20 33 11", consultation_hours: "Lun-Sam: 09:00-16:00", consultation_fee: 2500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français", "Tamazight"], rating: 4.5, review_count: 156, experience_years: 11, bio: "Endocrinologue spécialisée dans le diabète, les maladies thyroïdiennes et les troubles hormonaux.", available_today: true, latitude: 36.7509, longitude: 5.0564 },
  { first_name: "Abdelkader", last_name: "Ziani", title: "Dr.", specialty: "Gastro-entérologie", specialty_ar: "أمراض الجهاز الهضمي", address: "Polyclinique Tlemcen", commune: "Tlemcen", wilaya_id: 13, phone: "043 28 45 10", consultation_hours: "Dim-Jeu: 08:30-13:00", consultation_fee: 2500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.3, review_count: 112, experience_years: 17, bio: "Gastro-entérologue et hépatologue. Spécialisé dans le diagnostic endoscopique et le traitement des maladies digestives.", available_today: true, latitude: 34.8824, longitude: -1.3156 },
  { first_name: "Zineb", last_name: "Messaoudi", title: "Dr.", specialty: "Pédiatrie", specialty_ar: "طب الأطفال", sub_specialty: "Néonatologie", address: "EPH Tizi Ouzou", commune: "Tizi Ouzou", wilaya_id: 15, phone: "026 20 22 50", consultation_hours: "Lun-Sam: 08:00-14:00", consultation_fee: 1500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français", "Tamazight"], rating: 4.7, review_count: 248, experience_years: 9, bio: "Pédiatre néonatologue, spécialisée dans les soins des nouveau-nés prématurés et pathologiques. Passionnée par la santé de l'enfant kabyle.", available_today: false, latitude: 36.7112, longitude: 4.0450 },
  { first_name: "Malek", last_name: "Khoubou", title: "Dr.", specialty: "Rhumatologie", specialty_ar: "أمراض الروماتيزم", address: "Clinique Mehdi, Blida", commune: "Blida", wilaya_id: 9, phone: "025 43 78 00", consultation_hours: "Lun-Ven: 09:00-17:00", consultation_fee: 2000, accepts_cnas: true, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.4, review_count: 98, experience_years: 14, bio: "Rhumatologue spécialisé dans les maladies auto-immunes, arthrites et ostéoporose. Pratique l'infiltration guidée par échographie.", available_today: true, latitude: 36.4686, longitude: 2.8277 },
  { first_name: "Amina", last_name: "Sellami", title: "Dr.", specialty: "Médecine générale", specialty_ar: "طب عام", address: "Rue de la Paix, Batna", commune: "Batna", wilaya_id: 5, phone: "033 86 22 00", consultation_hours: "Lun-Sam: 08:30-19:30", consultation_fee: 1000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.3, review_count: 185, experience_years: 10, bio: "Médecin généraliste dynamique assurant un suivi complet pour toute la famille. Disponible pour les urgences médicales légères.", available_today: true, latitude: 35.5560, longitude: 6.1750 },
  { first_name: "Samir", last_name: "Benmansour", title: "Dr.", specialty: "Urologie", specialty_ar: "أمراض المسالك البولية", address: "Clinique Sainte Thérèse, Annaba", commune: "Annaba", wilaya_id: 23, phone: "038 82 11 00", phone2: "0661 77 55 33", consultation_hours: "Dim-Jeu: 09:00-13:00, 16:00-19:00", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.5, review_count: 143, experience_years: 16, bio: "Urologue chirurgien spécialisé dans la laparoscopie urologique, traitement des calculs rénaux et chirurgie prostatique.", available_today: true, latitude: 36.9100, longitude: 7.7600 },
  { first_name: "Nassima", last_name: "Touati", title: "Dr.", specialty: "Gynécologie-Obstétrique", specialty_ar: "أمراض النساء والتوليد", address: "Cabinet Médical El Hayat, Sétif", commune: "Sétif", wilaya_id: 19, phone: "036 84 80 00", consultation_hours: "Lun-Sam: 09:00-18:00", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.6, review_count: 267, experience_years: 13, bio: "Gynécologue obstétricienne dédiée à la santé féminine. Expertise en suivi de grossesse, échographie obstétricale et contraception.", available_today: true, latitude: 36.1940, longitude: 5.4100 },
  { first_name: "Hocine", last_name: "Djaafri", title: "Dr.", specialty: "Cardiologie", specialty_ar: "أمراض القلب", address: "Clinique du Palmier, Ouargla", commune: "Ouargla", wilaya_id: 30, phone: "029 71 22 10", consultation_hours: "Dim-Jeu: 09:00-13:00", consultation_fee: 3500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.6, review_count: 124, experience_years: 20, bio: "Cardiologue exerçant dans le sud algérien. Spécialisé dans l'échocardiographie et le traitement des maladies coronariennes.", available_today: false, latitude: 31.9539, longitude: 5.3353 },
  { first_name: "Fatiha", last_name: "Rezki", title: "Dr.", specialty: "Dermatologie", specialty_ar: "أمراض الجلد", address: "Cabinet El Baraka, Tizi Ouzou", commune: "Tizi Ouzou", wilaya_id: 15, phone: "026 21 88 00", consultation_hours: "Lun-Ven: 09:00-16:00", consultation_fee: 2500, accepts_cnas: false, accepts_casnos: false, languages: ["Arabe", "Français", "Tamazight"], rating: 4.7, review_count: 201, experience_years: 11, bio: "Dermatologue spécialisée en dermatologie pédiatrique et esthétique. Traitements de l'eczéma, vitiligo et cicatrices.", available_today: true, latitude: 36.7150, longitude: 4.0500 },
  { first_name: "Walid", last_name: "Khaldi", title: "Dr.", specialty: "Orthopédie-Traumatologie", specialty_ar: "جراحة العظام", address: "Clinique Ibn Rochd, Oran", commune: "Oran", wilaya_id: 31, phone: "041 36 44 00", consultation_hours: "Lun-Sam: 09:00-12:00, 15:00-18:00", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.4, review_count: 168, experience_years: 15, bio: "Chirurgien orthopédiste expert en arthroscopie, chirurgie du rachis et traumatologie sportive.", available_today: true, latitude: 35.7000, longitude: -0.6250 },
  { first_name: "Sara", last_name: "Hamida", title: "Dr.", specialty: "Ophtalmologie", specialty_ar: "طب العيون", address: "Clinique de la Vision, Constantine", commune: "Constantine", wilaya_id: 25, phone: "031 68 11 20", email: "dr.hamida.vision@gmail.com", consultation_hours: "Dim-Jeu: 08:00-12:00, 14:00-17:00", consultation_fee: 2500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.5, review_count: 189, experience_years: 12, bio: "Ophtalmologiste spécialisée en maladies cornéennes, glaucome et chirurgie réfractive LASIK.", available_today: true, latitude: 36.3700, longitude: 6.6200 },
  { first_name: "Lotfi", last_name: "Chouicha", title: "Dr.", specialty: "ORL - Oto-rhino-laryngologie", specialty_ar: "أمراض الأنف والأذن والحنجرة", address: "Polyclinique Guelma", commune: "Guelma", wilaya_id: 24, phone: "037 22 13 50", consultation_hours: "Dim-Jeu: 09:00-13:00, 15:00-18:00", consultation_fee: 2000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.3, review_count: 95, experience_years: 14, bio: "ORL spécialisé en audiologie, chirurgie de l'oreille moyenne et troubles de la déglutition.", available_today: true, latitude: 36.4622, longitude: 7.4315 },
  { first_name: "Karima", last_name: "Boussad", title: "Dr.", specialty: "Médecine générale", specialty_ar: "طب عام", address: "Cité 1200 Logements, Skikda", commune: "Skikda", wilaya_id: 21, phone: "038 76 00 22", consultation_hours: "Lun-Sam: 08:00-19:00", consultation_fee: 1000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.1, review_count: 78, experience_years: 8, bio: "Médecin généraliste accueillante et à l'écoute de ses patients. Suivi des maladies chroniques et vaccination.", available_today: true, latitude: 36.8783, longitude: 6.9003 },
  { first_name: "Ibrahim", last_name: "Guendouz", title: "Dr.", specialty: "Gastro-entérologie", specialty_ar: "أمراض الجهاز الهضمي", address: "CHU de Béjaïa", commune: "Béjaïa", wilaya_id: 6, phone: "034 22 55 00", consultation_hours: "Dim-Mer: 09:00-12:00", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français", "Tamazight"], rating: 4.6, review_count: 132, experience_years: 18, bio: "Gastro-entérologue et endoscopiste. Spécialisé dans les maladies inflammatoires de l'intestin et l'hépatite virale.", available_today: false, latitude: 36.7550, longitude: 5.0600 },
  { first_name: "Yasmina", last_name: "Boukhobza", title: "Dr.", specialty: "Psychiatrie", specialty_ar: "الطب النفسي", address: "Cabinet Médical El Wiam, Blida", commune: "Blida", wilaya_id: 9, phone: "025 41 55 77", consultation_hours: "Lun-Ven: 10:00-18:00", consultation_fee: 3000, accepts_cnas: false, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.9, review_count: 223, experience_years: 10, bio: "Psychiatre et psychothérapeute. Spécialiste en thérapies cognitivo-comportementales, burn-out et troubles de l'humeur.", available_today: true, latitude: 36.4700, longitude: 2.8300 },
  { first_name: "Sofiane", last_name: "Merad", title: "Dr.", specialty: "Neurologie", specialty_ar: "أمراض الأعصاب", address: "Clinique El Farabi, Tlemcen", commune: "Tlemcen", wilaya_id: 13, phone: "043 29 11 00", consultation_hours: "Lun-Jeu: 09:00-13:00, 15:00-18:00", consultation_fee: 3000, accepts_cnas: true, accepts_casnos: false, languages: ["Arabe", "Français"], rating: 4.4, review_count: 116, experience_years: 16, bio: "Neurologue spécialisé en céphalées, accidents vasculaires cérébraux et troubles du mouvement.", available_today: true, latitude: 34.8900, longitude: -1.3100 },
  { first_name: "Hanane", last_name: "Laroussi", title: "Dr.", specialty: "Endocrinologie", specialty_ar: "أمراض الغدد الصماء", address: "Polyclinique Boumerdès", commune: "Boumerdès", wilaya_id: 35, phone: "024 82 33 10", consultation_hours: "Lun-Ven: 09:00-16:00", consultation_fee: 2500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.3, review_count: 89, experience_years: 9, bio: "Endocrinologue dédiée au traitement du diabète de type 1 et 2, dysthyroïdies et troubles de la croissance.", available_today: true, latitude: 36.7631, longitude: 3.4765 },
  { first_name: "Redouane", last_name: "Hadjadj", title: "Dr.", specialty: "Médecine interne", specialty_ar: "الطب الباطني", address: "Hôpital de Ghardaïa", commune: "Ghardaïa", wilaya_id: 47, phone: "029 89 11 00", consultation_hours: "Dim-Jeu: 08:30-14:00", consultation_fee: 1500, accepts_cnas: true, accepts_casnos: true, languages: ["Arabe", "Français"], rating: 4.2, review_count: 67, experience_years: 12, bio: "Interniste expérimenté dans la prise en charge des pathologies chroniques du sud algérien.", available_today: false, latitude: 32.4897, longitude: 3.6744 },
];

async function seed() {
  console.log("Seeding wilayas...");
  for (const wilaya of wilayas) {
    await db.insert(wilayasTable).values(wilaya).onConflictDoNothing();
  }
  console.log(`Inserted ${wilayas.length} wilayas`);

  console.log("Seeding pharmacies...");
  for (const pharmacy of pharmacies) {
    await db.insert(pharmaciesTable).values(pharmacy).onConflictDoNothing();
  }
  console.log(`Inserted ${pharmacies.length} pharmacies`);

  console.log("Seeding doctors...");
  for (const doctor of doctors) {
    await db.insert(doctorsTable).values(doctor as any).onConflictDoNothing();
  }
  console.log(`Inserted ${doctors.length} doctors`);

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
